// <auto-generated />
using System;
using CocktailDebacle.Server.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailDebacle.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402104141_MakeStrVideoNullable")]
    partial class MakeStrVideoNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CocktailDebacle.Server.Models.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdDrink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrAlcoholic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrCreativeCommonsConfirmed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDrink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDrinkAlternate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDrinkThumb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrGlass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIBA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrImageAttribution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrIngredient9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsDE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsZH_HANS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrInstructionsZH_HANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrMeasure9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cocktails", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AcceptCookies")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DbUser");
                });
#pragma warning restore 612, 618
        }
    }
}
