version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AcTua2025 # Cambia la password
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  backend:
    build:
      context: ./CocktailDebacle.Server
      dockerfile: Dockerfile
    container_name: cocktail_backend
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - backend

  frontend:
    build:
      context: ./cocktaildebacle.client
      dockerfile: Dockerfile
    container_name: cocktail_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - backend

volumes:
  sql_data:

networks:
  backend:
    driver: bridge